# This workflow will install Python dependencies and run tests with a single version of Python.

name: E01 Python Application

on:
    push:
        branches: [ $default-branch ]
    pull_request:
        branches: [ $default-branch ]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Setup Python 3.11
          uses: actions/setup-python@v3
          with:
            python-version: "3.11"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Lint with flake8
          run: |
            # Stop the build if there are Python syntax errors or undefined names.
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings.
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        - name: Test with pytest
          run: |
            pytest
